name: Check collaborator

on:
  pull_request:
    types:
      - opened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          collaborators=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/collaborators" | \
          jq -r '.[].login' | tr '\n' ' ')
          pr_author=${{ github.event.pull_request.user.login }}
          if echo "$collaborators" | grep -q "$pr_author"; then
            echo "PR author is a collaborator"
          else
            echo "PR author is not a collaborator"
            exit 1
          fi
